apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: common
data:
  default.conf: |
    server {
      listen 80;
      
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
    }
  rabbitmq.conf: |
    server {
      listen 80;
         
      location / {
        proxy_pass http://rabbitmq-service.common.svc.cluster.local:15672/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    } 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx-proxy
        image: nginxproxy/nginx-proxy:1.4.0-75-g3d61f47
        volumeMounts:
        - name: docker-socket-volume
          mountPath: /tmp/docker.sock
          readOnly: true
      volumes:
      - name: docker-socket-volume
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: common
spec:
  selector:
    app: nginx-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
