#apiVersion: v1
#kind: Secret
#metadata:
#  name: redis-secret
#  namespace: common
#type: Opaque
#data:
#  redis-password: QWJjLi4xMjM= #Abc..123 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
#        env:
#        - name: REDIS_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: redis-secret
#              key: redis-password
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: common
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
