apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: common
  labels:
    deploy: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8-management-alpine
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: admin
            - name: RABBITMQ_DEFAULT_PASS
              value: Abc..123
          ports:
            - containerPort: 5672  # Puerto AMQP
            - containerPort: 15672  # Puerto de la interfaz de gestión HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: common
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: LoadBalancer
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: rabbitmq-ingress
#spec:
#  rules:
#    - host: 20.12.121.124  # Cambia esto a tu dominio o dirección IP
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: rabbitmq-service
#                port:
#                  number: 15672  # Puerto de la interfaz de gestión RabbitMQ