apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: common
data:
  default.conf: |
server {
  listen 80;
  server_name localhost;

  #listen 443 default_server ssl;
  #ssl_certificate           /etc/nginx/certs/-public.crt;
  #ssl_certificate_key       /etc/nginx/certs/-private-key.pem;

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
  }

  location /rabbitmq {
    proxy_pass http://rabbitmq-service.common.svc.cluster.local:15672/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

    location /eureka {
    proxy_pass http://eureka-service.common.svc.cluster.local:8761/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: common
  labels:
    deploy: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: common
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer